# Generated by Django 5.2.9 on 2026-01-04 16:04

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_blog_body_alter_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Blog Body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Short Description'),
        ),
    ]
